POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: generate token from login and put here

{
    "content":"Middleware : userExtraction and tokenExtraction",
    "important":true,
    "userId":""
}